#!/bin/sh
# Script de inicialização feito por Protimus.

PATH=./:$PATH

L_SRV=login-server
C_SRV=char-server
M_SRV=map-server

print_start() {
echo "brAthena Iniciando..."
echo "            brAthena (c) 2009 ~ 2013"
echo ""
echo "checando..."
}

check_files() {

    for i in ${L_SRV} ${C_SRV} ${M_SRV}
    do
        if [ ! -f ./$i ]; then
            echo "$i Não existe ou não pode ser executado."
            echo "Desligado! Verifique seu compilador."
            exit 1;
        fi
    done

#    more << EOF
echo "Checagem completa."
#EOF
}
    

case $1 in
    'start')
        print_start
        check_files
		
		exec ./${L_SRV}&
	echo $! > .${L_SRV}.pid
		exec ./${C_SRV}&
	echo $! > .${C_SRV}.pid
		exec ./${M_SRV}&
	echo $! > .${M_SRV}.pid
	
        echo "O brAthena foi iniciado!"
;;
    'stop')
        for i in .${L_SRV}.pid .${C_SRV}.pid .${M_SRV}.pid
	    do
		if [ -e ./$i ]; then
		    kill $(cat $i)
		    rm $i
		fi
	    done
;;
	'restart')
        $0 stop
        $0 start
;;
    'gdb')
        print_start
        check_files
		
		ulimit -c unlimited
		exec ./${L_SRV}& 
		exec ./${C_SRV}& 
		gdb map-server map-server.core
        echo "O brAthena foi iniciado em modo de depuração!"
		gdb> bt full
;;
    *)
        echo "Modo de usar: brathena-start { start | stop | restart | gdb}"
;;
esac